### ISSUE TITLE
Usage with ReactJs

### ISSUE THREAD

**Issue by MohammedAijaaz** [byeolbit/translucent#8]
Greetings, I have issues using this in ReactJs, can you give a guide on this.
Anyways, great work!

**Comment by byeolbit** [comment]
Thanks!
Here is simple example code for ReactJS.
I hope this could be help for you.

Install translucent from npm
```
$ npm install --save translucent
```

SampleComponent.js
```js
import React, { Component } from 'react';
import {Translucent} from 'translucent';
import './SampleComponent.css';

class SampleComponent extends Component {
  componentDidMount() {
    this.translucent = new Translucent(this.refs.targetEl);
  }

  render() {
    return (
      <div className="bg-element">
        <div ref="targetEl" className="content-wrapper">
          <div className="contents">
            <h1>Welcome to React</h1>
            // contents here...
          </div>
        </div>
      </div>
    );
  }
}

export default SampleComponent;
```

SampleComponent.css
```css

.bg-element {
  width: 100%;
  height: 100vh;
  background-image: url('bg.jpeg');
}

.content-wrapper {
  width: 300px;
  height: 480px;
  margin: 0 auto;
}

.contents {
  width: 300px;
  height: 480px;
}
```
Since Translucent doesn't have a component for ReactJS, you have to get element reference to apply translucent effect. 

I have a future plan to support Vue, React, and Angular.
